version: '3'

services:
  app:
    container_name: webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    init: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
